### ISSUE TITLE
oSSkey里面配置上传图片路径好像没什么用，读取值是从jsp目录下config.json读取的配置，改里面值才行

### ISSUE THREAD

**Issue by Imtonoo** [XieXianbin/UEditor-for-aliyun-OSS#7]

**Comment by Imtonoo** [comment]
初始化ueditor传imgepathformat好像也没什么用，真是怪了

**Comment by xiexianbin** [comment]
UEditor-for-aliyun-OSS的修改思路是在不影响ueditor的情况下，修改元ue的后端存储。所以真正生效的目录配置文件是config.json的配置。
